### ISSUE TITLE
Adopt MIT license

### ISSUE THREAD

**Issue by ghost** [mrsyzygy/nerva-docs#4]
During docs development I have neglected to assign a license to this repository. If all contributors to date consent, we will release the existing and future content under the MIT license.

**Comment by iamamyth** [comment]
I agree to licensing my prior (and future) contributions under the MIT license.

**Comment by ghost** [comment]
With the consent of all who have assisted with my contributions, I agree to licensing my prior (and future) contributions under the MIT license.
